# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Android Audit
email: hello@karumi.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/AndroidAudit" # the subpath of your site, e.g. /blog
url: "http://karumi.github.io/" # the base hostname & protocol for your site
twitter_username: gokarumi
github_username:  karumi
output: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM